export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_TYPES_POKEMONS = "GET_TYPES_POKEMONS";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const ORDER_ALPHABET = "ORDER_ALPHABET";
export const ORDER_ATTACK = "ORDER_ATTACK";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_POKE_CREATED = "FILTER_POKE_CREATED";

